# Config file for automatic testing at travis-ci.org

language: python
python:
  - 3.6

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
before_install:
  - pip install --upgrade pip
  - pip install --upgrade wheel
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set show_channel_urls true
  - conda update conda
  - conda config --add channels conda-forge --force
  - conda create --quiet --name invest-ucm-calibration python=$TRAVIS_PYTHON_VERSION
  - source activate invest-ucm-calibration
  - conda install -c conda-forge 'gdal<3.0' rtree 'shapely<1.7.0'
  - conda info --all
  - conda list  
install:
  - pip install -r requirements-dev.txt
  - pip install -r requirements.txt

# command to run tests, e.g. python setup.py test
script:
  - coverage run --source invest_ucm_calibration -m py.test

after_success:
  - coverage report -m
  - coveralls

# deploy new versions to PyPI
deploy:
  provider: pypi
  on:
    tags: true
    python: 3.6
  user: martibosch
  password:
    secure: lgIDLN7kf6crTRQFcp2ZhcuTOc2e1L21I7p8t7p3VvbddBtAfnvPFWU52vdgK5SK2tX8fH+2L3bumvFs9JjUeWoYNitxp5lINa6bW9mMlktILpemEz9k/d7zxh0r2+d1kVNn49Rd7y7U1TUHlFecyhQ2STyflhHaykUsr2/B/kN1AY/2nAArWcT55Iamlh5ZiuzHxJ5OOlluPToP45ynMHlhsVLD2IQR9+NMV93n1kmhUAodUHCYu/JW8aPfLbycPux0RjLFi8SdD51yLEDI6QUJEh3aN0HY8sRN9Wj/DAI+wilAkfeGDZl3yhZHzVFYa7/Oi4gVvoEY7fXsuu9hTiaBBig/H6MMhcDX0oKzIzvvZQQ7KdAxNjburLgXAn33uJpv23cqclyRpGvBhu2HqfUxOxm/I5Vp8bq/OtPAf4ETzZ+HZiEKNgF68WJPbRw0OrXd8rOPbiUe+VTm9BhyLjsPiU9LrVvkGPSYID6yDX3p6kvx6RCKkE1+RoCEx7pNl2EbDT/+Ym/WyPAZjD/KlhbtBO8CBsCv/LwYzH8QPNe4Ypq9fc10jtYx7MiQu65fFVHRkSidzLECGbtUtWlWr0h/pxny5yTJ5FsT4d9p6Fkadhvpzsi58BRQHqyQcQk1VqUtYRF3QhfMHCQ+eB1612ypBGsOyHo0LeoyjJIrhLY=
