site_name: InVEST UCM calibration
# site_url: http://www.jieyu.ai
repo_url: https://github.com/martibosch/invest_ucm_calibration
repo_name: invest_ucm_calibration
#strict: true
nav:
  - home: index.md
  - User guide: usage.md
  - Reference guide (API): api.md
  - Command-line interface (CLI): cli.md    
  - Contributing: contributing.md
  - history: history.md
theme:
  name: readthedocs
  language: en
  #logo: assets/logo.png
extra_css:
  - css/extra.css
plugins:
  - include-markdown
  - search:
      lang: en
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_section_style: list
            docstring_style: numpy            
            show_bases: false
            show_source: false
markdown_extensions:
  - mkdocs-click            
watch:
  - invest_ucm_calibration
  # to enable disqus, uncomment the following and put your disqus id below
  # disqus: disqus_id
# uncomment the following and put your google tracking id below to enable GA
#google_analytics:
  #- UA-xxx
  #- auto
